#!/bin/bash

for dir in "main" "p1" "p2" "p2"; do
    plot_dir=$(pwd)/parallel/${dir}
    echo $plot_dir
    afl-plot $plot_dir output-$dir
    # for i in $(ls $(pwd)/parallel/${dir}/crashes/id:*); do
    #     output=$(flacon/flacon -s ${i} 2>&1)
    #     if [[ "$output" ]]
    #     # echo $output
    # done
done

